import { z } from "zod";

export const ActivitySchema = z.object({
  Title: z.string(),
  slug: z.string().regex(/^[a-zA-Z0-9_-]*$/).min(5).max(20),
  categorie: z.string(),
  Information: z.string(),
  Date: z.date(),
  userWanted: z.string(),
  Icon: z.string(),

});

export type ActivityType = z.infer<typeof ActivitySchema>

export const activityCategories = [
  "Outdoor Sports",
  "Indoor Sports",
  "Board Games",
  "Cultural Events",
  "Music Concerts",
  "Movie Nights",
  "Cooking Classes",
  "Art and Craft",
  "Dance Workshops",
  "Hiking and Trekking",
  "Photography Tours",
  "Escape Rooms",
  "Karaoke Nights",
  "Trivia Nights",
  "Beach Parties",
  "Barbecue Gatherings",
  "Picnic in the Park",
  "Amusement Park Visits",
  "Live Theater Shows",
  "Group Fitness Classes",
  "Yoga Sessions",
  "Wine Tasting Events",
  "Book Club Meetings",
  "Bike Riding",
  "Community Volunteer Work",
  "Group Meditation",
  "Museum Tours",
  "Zoo Visits",
  "Group Painting Sessions",
  "Stand-Up Comedy Shows",
  "Fishing Trips",
  "Live Music Performances",
  "DIY Craft Workshops",
  "Game Nights",
  "Camping Trips",
]

export const icons = [
  "Beef",
  "Beer",
  "Bike",
  "Castle",
  "Clapperboard",
  "Dumbbell",
  "Drill",
  "Fish",
  "Footprints",
  "Gamepad2",
  "ImageMinus",
  "MountainSnow",
  "Music",
  "Palette",
  "PartyPopper",
  "Puzzle",
  "UtensilsCrossed",
  "TentTree",
  "Theater",
]