import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/src/lib/utils";
import { Providers } from "./Providers";
import { Suspense } from "react";
import { NavigationEvents } from "@/src/components/navigation-events";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Mate finder",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body className={cn(inter.className, 'h-full')}><Providers>
        {children}
        <Suspense fallback={null}>
          <NavigationEvents />
        </Suspense></Providers>
      </body>
    </html>
  );
}
