import { z } from "zod";

export const UserSchema = z.object({
  name: z.string(),
  image: z.string().optional(),
  age: z.date(),
  username: z.string().regex(/^[a-zA-Z0-9_-]*$/).min(5).max(20), 
  location: z.string(), 
});

export type UserType = z.infer<typeof UserSchema>;

export const LocationCategories = [
  "Ain",
  "Aisne",
  "Allier",
  "Alpes-de-Haute-Provence",
  "Hautes-Alpes",
  "Alpes-Maritimes",
  "Ardeche",
  "Ardennes",
  "Ariege",
  "Aube",
  "Aude",
  "Aveyron",
  "Bas-Rhin",
  "Bouches-du-Rhône",
  "Calvados",
  "Cantal",
  "Charente",
  "Charente-Maritime",
  "Cher",
  "Correze",
  "Corse-du-Sud",
  "Cote-dOr",
  "Cotes-d-Armor",
  "Creuse",
  "Deux-Sevres",
  "Dordogne",
  "Doubs",
  "Drome",
  "Essonne",
  "Eure",
  "Eure-et-Loir",
  "Finistère",
  "Gard",
  "Haute-Corse",
  "Haute-Garonne",
  "Haute-Loire",
  "Haute-Marne",
  "Hautes-Pyrénées",
  "Haute-Saone",
  "Haute-Savoie",
  "Haute-Vienne",
  "Hauts-de-Seine",
  "Haut-Rhin",
  "Gers",
  "Gironde",
  "Herault",
  "Ille-et-Vilaine",
  "Indre",
  "Indre-et-Loire",
  "Isere",
  "Jura",
  "Landes",
  "Loir-et-Cher",
  "Loire",
  "Loire-Atlantique",
  "Loiret",
  "Lot",
  "Lote-et-Garonne",
  "Lozere",
  "Maine-et-Loire",
  "Manche",
  "Marne",
  "Mayenne",
  "Meurthe-et-Moselle",
  "Meuse",
  "Morbihan",
  "Moselle",
  "Nievre",
  "Nord",
  "Oise",
  "Orne",
  "Paris",
  "Pas-de-Calais",
  "Puy-de-Dome",
  "Pyreenees-Atlantiques",
  "Pyreenees-Orientales",
  "Rhône",
  "Saone-et-Loire",
  "Sarthe",
  "Savoie",
  "Seine-Maritime",
  "Seine-et-Marne",
  "Yvelines",
  "Somme",
  "Tarn",
  "Tarn-et-Garonne",
  "Territoire-de-Belfort",
  "Var",
  "Vaucluse",
  "Vendee",
  "Vienne",
  "Vosges",
  "Yonne",
];