import { z } from "zod";

export const UserSchema = z.object({
  name: z.string(),
  image: z.string().optional(),
  age: z.date(),
  username: z.string(), 
  location: z.string(), 
});

export type UserType = z.infer<typeof UserSchema>;

export const LocationCategories = [
  "Ain",
  "Aisne",
  "Allier",
  "Alpes-de-Haute-Provence",
  "Hautes-Alpes",
  "Alpes-Maritimes",
  "Ardèche",
  "Ardennes",
  "Ariège",
  "Aube",
  "Aude",
  "Aveyron",
  "Bas-Rhin",
  "Bouches-du-Rhône",
  "Calvados",
  "Cantal",
  "Charente",
  "Charente-Maritime",
  "Cher",
  "Corrèze",
  "Corse-du-Sud",
  "Côte-d'Or",
  "Côtes-d'Armor",
  "Creuse",
  "Deux-Sèvres",
  "Dordogne",
  "Doubs",
  "Drôme",
  "Essonne",
  "Eure",
  "Eure-et-Loir",
  "Finistère",
  "Gard",
  "Haute-Corse",
  "Haute-Garonne",
  "Haute-Loire",
  "Haute-Marne",
  "Hautes-Pyrénées",
  "Haute-Saône",
  "Haute-Savoie",
  "Haute-Vienne",
  "Hauts-de-Seine",
  "Haut-Rhin",
  "Gers",
  "Gironde",
  "Hérault",
  "Ille-et-Vilaine",
  "Indre",
  "Indre-et-Loire",
  "Isère",
  "Jura",
  "Landes",
  "Loir-et-Cher",
  "Loire",
  "Loire-Atlantique",
  "Loiret",
  "Lot",
  "Lot-et-Garonne",
  "Lozère",
  "Maine-et-Loire",
  "Manche",
  "Marne",
  "Mayenne",
  "Meurthe-et-Moselle",
  "Meuse",
  "Morbihan",
  "Moselle",
  "Nièvre",
  "Nord",
  "Oise",
  "Orne",
  "Paris",
  "Pas-de-Calais",
  "Puy-de-Dôme",
  "Pyrénées-Atlantiques",
  "Pyrénées-Orientales",
  "Rhône",
  "Saône-et-Loire",
  "Sarthe",
  "Savoie",
  "Seine-Maritime",
  "Seine-et-Marne",
  "Yvelines",
  "Somme",
  "Tarn",
  "Tarn-et-Garonne",
  "Territoire-de-Belfort",
  "Var",
  "Vaucluse",
  "Vendée",
  "Vienne",
  "Vosges",
  "Yonne",
];